/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nicai_mytestjni_HelloJNI */

#ifndef _Included_com_nicai_mytestjni_HelloJNI
#define _Included_com_nicai_mytestjni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nicai_mytestjni_HelloJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_nicai_mytestjni_HelloJNI_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
